function [fitresult, gof] = s07_2x15_2cm_Rplotfunc(kPa_s07_2x15, R_s07_2x15)
%CREATEFIT(KPA_S07_2X15,R_S07_2X15)
%  Create a fit.
%
%  Data for 's07_2x15' fit:
%      X Input: kPa_s07_2x15
%      Y Output: R_s07_2x15
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 26-Jul-2023 00:09:47


%% Fit: 's07_2x15'.
[xData, yData] = prepareCurveData( kPa_s07_2x15, R_s07_2x15 );

% Set up fittype and options.
ft = fittype( 'exp1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.0315470901084234 0.106954298370785];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
% figure( 'Name', 's07_2x15' );
h2x15 = plot( fitresult, xData, yData );
set(h2x15,'Color','#808080');
% legend( h, 'R_s07_2x15 vs. kPa_s07_2x15', 's07_2x15', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'kPa_s07_2x15', 'Interpreter', 'none' );
ylabel( 'R_s07_2x15', 'Interpreter', 'none' );
grid on


