function [fitresult, gof] = s07_3x15_2cm_Rplotfunc(kPa_s07_3x15, R_s07_3x15)
%CREATEFIT(KPA_S07_3X15,R_S07_3X15)
%  Create a fit.
%
%  Data for 'untitled fit 2' fit:
%      X Input: kPa_s07_3x15
%      Y Output: R_s07_3x15
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 24-Jul-2023 23:30:21


%% Fit: 'untitled fit 2'.
[xData, yData] = prepareCurveData( kPa_s07_3x15, R_s07_3x15 );

% Set up fittype and options.
ft = fittype( 'exp1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.0104698397573706 0.170018435909771];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
% figure( 'Name', 'untitled fit 2' );
h3x15 = plot( fitresult, xData, yData );
set(h3x15,'Color','#FF00FF');
% legend( h, 'R_s07_3x15 vs. kPa_s07_3x15', 'untitled fit 2', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
xlabel( 'kPa_s07_3x15', 'Interpreter', 'none' );
ylabel( 'R_s07_3x15', 'Interpreter', 'none' );
grid on


