#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Apr  4 22:02:20 2023

@author: cocolee
"""

from bs4 import BeautifulSoup
import requests
import smtplib
import time
import datetime


#%%
# Connect to website

URL = 'https://www.amazon.co.uk/echo-dot-2022/dp/B09B96TG33/ref=zg_bs_amazon-devices_sccl_6/258-4089216-8575334?psc=1'

headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36", 
    "X-Amzn-Trace-Id": "Root=1-642c9180-4f2e53e1691eef4147bb2546"}

page = requests.get(URL, headers=headers)

soup1 = BeautifulSoup(page.content, "html.parser")

soup2 = BeautifulSoup(soup1.prettify(),"html.parser")

#%%
title = soup2.find(id='productTitle').get_text()
price1 = soup2.find(attrs={'class': 'a-price-whole'}).get_text()
price2 = soup2.find(attrs={'class': 'a-price-fraction'}).get_text()
price = (price1+price2).replace('\n','').replace(" ",'')


price = price.strip()

title = title.strip()

print(title)
print(price)

#%%
# the time the data is scraped

import datetime

today = datetime.date.today()

print(today)

#%%

import csv

header = ['Title','Price','Date']
data = [title,price,today]

with open('AmazonWebScraper.csv','w',newline='', encoding='UTF8') as f:

    #w = write #newline='', so it doesn't create space between

    writer = csv.writer(f) #opening the file
    writer.writerow(header) #writing the header
    writer.writerow(data) #writiing the data

#%%

import panda as pd



